export const items = [
  {
    id: 1,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 2,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 3,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 4,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 5,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 6,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 7,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 8,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 9,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
  {
    id: 10,
    category: "cloths",
    name: "리본 써지컬 목걸이",
    percent: "30%",
    price: "6,600",
    image: "../src/assets/image.png",
  },
];
